name: Build & Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            killall node
            rm -rf vinyl 
            git clone https://github.com/JCrews253/vinyl.git
            cd vinyl
            touch .env
            cat << EOF >.env
            TOKEN=${{secrets.DISCORD_TOKEN}}
            DISCORD_APPLICATION_ID=${{secrets.DISCORD_APPLICATION_ID}}
            LAVA_HOST=${{secrets.LAVA_HOST}}
            LAVA_PASS=${{secrets.LAVA_PASS}}
            SSH_HOST=${{secrets.SSH_HOST}}
            SSH_KEY=${{secrets.SSH_KEY}}
            SSH_USERNAME=${{secrets.SSH_USERNAME}}
            NODE_ENV=production
            EOF
            npm install
            npm run build
            nohup node build/index.js </dev/null &>/dev/null &
            echo 'Deployment successful to digital ocean'
