name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            rm -rf vinyl 
            git clone https://github.com/JCrews253/vinyl.git
            cd vinyl
            touch .env
            cat << EOF >.env
            token=${{secrets.DISCORD_TOKEN}}
            EOF
            npm install
            npm run build
            echo 'Deployment successful to digital ocean' 
